### ISSUE TITLE
Weight pushing in Transformer class

### ISSUE THREAD

**Issue by giacomocamposampiero** [rycolab/aflt-f2022#10]
In the `_push` method of Transformer class before returning the pushed FSA you assert whether the FSA is pushed or not.

However, we might want to push the FSA with weights that don't necessarily make the FSA pushed (e.g. in the code for question 2 of Assignment 5), that is whenever we push the FSA with weights that aren't strictly backward weights. 

Link to the LOC for reference:
https://github.com/rycolab/aflt-f2022/blob/7567af1e29c41158aafb1e1859b86aace2ceade3/rayuela/fsa/transformer.py#L50

Proposed fix: #11

**Comment by giacomocamposampiero** [comment]
#11

**Comment by dveni** [comment]
702394843c15b2da5fd2f3c6f10291a4124a3fd2 should has solved this
